"""added category & shopimages

Revision ID: 04ef65e66bb8
Revises: 5a4ecd953451
Create Date: 2026-08-09 09:45:52.936485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ef65e66bb8'
down_revision: Union[str, Sequence[str], None] = '5a4ecd953451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('logo_path', sa.String(length=500), nullable=True))
    op.add_column('shops', sa.Column('logo_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'logo_path')
    op.drop_column('categories', 'logo_path')
    # ### end Alembic commands ###
