"""updated cart

Revision ID: 506b2a6fcd05
Revises: 9cadb351c75c
Create Date: 2026-08-28 20:17:10.651085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506b2a6fcd05'
down_revision: Union[str, Sequence[str], None] = '9cadb351c75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'carts', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='unique')
    # ### end Alembic commands ###
