"""added products

Revision ID: 5a4ecd953451
Revises: ff05c0e183d0
Create Date: 2026-08-08 10:16:44.662270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4ecd953451'
down_revision: Union[str, Sequence[str], None] = 'ff05c0e183d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_translations',
    sa.Column('attribute_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.Column('lang', sa.Enum('ENGLISH', 'RUSSIAN', 'UZBEK', name='languageenum', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_values',
    sa.Column('attribute_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shops',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_value_translations',
    sa.Column('attribute_value_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.Column('lang', sa.Enum('ENGLISH', 'RUSSIAN', 'UZBEK', name='languageenum', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_translations',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('lang', sa.Enum('ENGLISH', 'RUSSIAN', 'UZBEK', name='languageenum', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variations',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=320), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('price > 0'),
    sa.CheckConstraint('stock_quantity >= 0'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variant_attribute_values',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('attribute_value_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', 'attribute_value_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant_attribute_values')
    op.drop_table('product_variations')
    op.drop_table('product_translations')
    op.drop_table('products')
    op.drop_table('attribute_value_translations')
    op.drop_table('shops')
    op.drop_table('attribute_values')
    op.drop_table('attribute_translations')
    op.drop_table('attributes')
    # ### end Alembic commands ###
